apiVersion: v1
kind: Secret
metadata:
    name: github-secret
    namespace: renovate
stringData:
    renovate-token: ENC[AES256_GCM,data:BcIJKKjnNnQlmqZvJDvpgkWRXnnfo0gW0hEOR2lwzzh/B1E7fKv5vCmkcSLwOYsLOeH/lBIeG0vfyjDmpi9x0YfFyJTJ/WP2pXgDsFWCMgQFhDornWJY1Mf0iQ89,iv:SOXDGts1SnQk5J9zNFk6uUKhQjyD63kKycXTgvzj8yE=,tag:KsmRHgaLIVjRhwF0D/77lw==,type:str]
sops:
    age:
        - recipient: age1wtyjfrs45k4dkwcu0ktle5u0pw7lsj8tk7d65f4t6j7tl43vavsqrwnak5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5aWR1Uk44aENnbG1EVm9C
            SytjeVJvbHNpMEdnTlAybG1nM3pBWGNMVFRnClB2Mk5IY09zaTNlQ2M1WUs0Ympi
            MWZCYW9pOWdBUG13bm0yNmN4VDB6TFEKLS0tIGdkcGY5eUFaMi84U2trV3lZNE5G
            M0EvSnFWK1FqaWdodkwwcllXZm01aE0KRfXLj3HsmienUhXCGJdv90xhlDjij+da
            MKgP+t4EYPRXg/jULXemw+cAZJKmkXHILUrlBEm+pCxkFJ4N6VqeUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-25T15:01:43Z"
    mac: ENC[AES256_GCM,data:cW0CkFvjooKEgcYuxsyRaelL3TMKJ+f9ZS5eaEuTMTANAFCZyxFs+V5f4GJ1UQsXwJq+OOfdRB5eDrcIzESep12HkfEoO9voWEKCfDV8P07j9YkJn1OfkrzT+INBqWw3DOJjSC6rZEa6UoyZfqEzZ9bgMOM/HPpqnjJBllPVMdo=,iv:R+quELw6vbdg0PQqCcbJIDPWQ9vVwSgCAeD9BoKydG8=,tag:T3JQJHv56wnOVv3NAO4SIA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
