apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home-automation
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/
    allow_anonymous true
    listener 1883
