apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: ""
  services.yaml: |
    - Home Automation:
      - Zigbee Radio (SLZB-MR3):
          href: http://192.168.100.149
          icon: si-zigbee
          description: Zigbee Radio management interface
    - Cluster Management:
      - Technitium DNS:
          href: http://dns.millward-yuan.net:5380/
          description: Technitium DNS web interface
          icon: sh-technitium
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
