---
clusterName: homelab
endpoint: https://192.168.100.10:6443
talosVersion: v1.11.2
allowSchedulingOnMasters: true
nodes:
  - hostname: main
    controlPlane: true
    ipAddress: 192.168.100.10
    installDisk: /dev/nvme0n1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/thunderbolt
