---
clusterName: homelab
endpoint: https://192.168.100.10:6443
talosVersion: v1.11.3
allowSchedulingOnMasters: true
nodes:
  - hostname: main
    controlPlane: true
    ipAddress: 192.168.100.10
    installDisk: /dev/nvme0n1
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/thunderbolt
patches:
  - |-
    machine:
      kubelet:
        extraArgs:
          rotate-server-certificates: true
    cluster:
      extraManifests:
        - https://raw.githubusercontent.com/alex1989hu/kubelet-serving-cert-approver/main/deploy/standalone-install.yaml
        - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml