apiVersion: v1
kind: Secret
metadata:
    name: external-dns-tsig-secret
    namespace: external-dns
data:
    tsig-key: ENC[AES256_GCM,data:z+zdBoOdZFuy93hM7RYRsVdCxZ04UaziRSkS2mLBrFNoW1LlZ0T40txmUEk=,iv:1Al91cYMkc84/1XdSrMTqJ6CVx3paQCXWLwQFQr1ksY=,tag:n9U8DdV8oXDF+VkTW5ljIA==,type:str]
sops:
    age:
        - recipient: age1y6ap7j9jfew80qfc2anyxpx486ajfn3p6huzmdjxs4mxjfu4demqhxfzj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTkxTM0hVSUcwczRpbDJ3
            WkxXK083anBwYys5S0wwVmRvRjFEaS9IOHlVCmt5cFptVEFpaE4xMk9OVkpSOHdF
            MzZXdjYxUVFRTERnTXRpU3pvamo4THMKLS0tIHZ6ZEVaMEs1M1BjaU9ZRlNtS0xH
            T2FOQkRMN0YwQmJGbHd3am5lNjFwTjAKVqFFzx9QV90ijeePuJ+15Drnq1DAje+s
            5xTANBLc2zB6B6YN5yUoDvcrMs7iqK/E7osx+v5YT/+AeehvZ66v0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-09T17:09:18Z"
    mac: ENC[AES256_GCM,data:P8aNSU2/wFyqyc23T6cbz921OMKIHnhg4fP5WT8M8+aehuGtLXX7fm0USE956yfU4uXXvX8MEXi1k1ngF+27z/v12jDd/3j6Ew/KIVCeceLWEbd6H86eaLCb4HPztjkwabPLR/3lF9zApJ4AZUcGnS1Ux+/l9gH5dOx+zIY1IJY=,iv:KFWAYeQ37iY2bH57UJWvtlM17nxaiyIKfNFvA1igv7M=,tag:ZDF2rPIfCGjSay+X2RusYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
