apiVersion: v1
kind: Service
metadata:
  name: technitium-dns
  namespace: technitium
  annotations:
    metallb.io/loadBalancerIPs: 192.168.100.20
    external-dns.alpha.kubernetes.io/hostname: dns.millward-yuan.net.
spec:
  type: LoadBalancer
  selector:
    app: technitium-dns
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 1053
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 1053
    - name: web
      port: 5380
      protocol: TCP
      targetPort: 5380
