apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  releaseName: traefik
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 37.1.1
      sourceRef:
        kind: HelmRepository
        name: traefik-charts
        namespace: flux-system
  values:
    deployment:
      kind: DaemonSet    
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true 
    providers:
      kubernetesGateway:
        enabled: true
    persistence:
      enabled: false # Disabled as cert-manager handles cert storage
    gateway:
      listeners:
        web:
          namespacePolicy:
            from: All
