apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  namespace: home-automation
  annotations:
    external-dns.alpha.kubernetes.io/hostname: homeassistant.millward-yuan.net
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: "Home Assistant web UI"
    gethomepage.dev/icon: "mdi:home-assistant"
spec:
  rules:
    - host: homeassistant.millward-yuan.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeassistant
                port:
                  number: 8123