namespace: metallb-system

resources:
  - github.com/metallb/metallb/config/native?ref=v0.15.2

patches:
  - target:
      kind: DaemonSet
      name: speaker
    # Add --ignore-exclude-lb to speaker args to prevent exclusion of control-nodes running workloads
    # https://github.com/siderolabs/talos/discussions/10118
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --ignore-exclude-lb