apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: traefik
spec:
  secretName: wildcard-certificate
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: '*.millward-yuan.net'
  dnsNames:
    - '*.millward-yuan.net'
