apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zigbee2mqtt
  namespace: zigbee2mqtt
spec:
  interval: 30m
  chart:
    spec:
      chart: zigbee2mqtt
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: zigbee2mqtt
        namespace: flux-system
      interval: 30m
  values:
    # Enable persistent storage
    statefulset:
      storage:
        enabled: true
        volumeMounts:
          - name: config
            mountPath: /app/data
        volumes:
          - name: config
            persistentVolumeClaim:
              claimName: zigbee2mqtt-config
    # Configuration for SLZB-MR3 TCP connection
    zigbee2mqtt:
      serial:
        # Location of SLZB-MR3 - TCP connection
        port: tcp://192.168.100.149:6638
        baudrate: 115200
        adapter: ember
        # Disable green led?
        disable_led: false
      # Set output power to max 20
      advanced:
        transmit_power: 20
      # MQTT configuration
      mqtt:
        server: mqtt://mosquitto.home-automation.svc.cluster.local:1883
        base_topic: zigbee2mqtt
        client_id: zigbee2mqtt
        include_device_information: true
      frontend:
        enabled: true
      homeassistant:
        enabled: true
