apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt-config
  namespace: zigbee2mqtt
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn