apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: v1.18.0
  interval: 15m
  releaseName: cert-manager
  targetNamespace: cert-manager
  install:
    createNamespace: true
  values:
    installCRDs: true