apiVersion: v1
kind: Secret
metadata:
    name: external-dns-tsig-secret
    namespace: external-dns
stringData:
    tsig-key: ENC[AES256_GCM,data:av1cKO0jGkcawxCVS9J76QKQvOZ1w7zR7YZjRabnwL/KsimLYNpp81tlMwM=,iv:LyIqvuxkN8dO4QJV1Eek2SAixdFphsKYKFoY1Z+usDI=,tag:9iQJT6orfOQ6Yu3cgTzT+g==,type:str]
sops:
    age:
        - recipient: age1y6ap7j9jfew80qfc2anyxpx486ajfn3p6huzmdjxs4mxjfu4demqhxfzj4
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeDBRQWJGT0tHRmpLODNF
            Wml1NDB3ajZ2dUEybTZDMzNYeFVxUkpmOGlnClEzYTdhbWNlY1dYQUdFaUxWaVRY
            V2pzeE9JUE13bkRwQTV2bUhabmRnWTAKLS0tIEoydzM5M2FpV202aDUxQ1N0Znhi
            VzYzeDBrOWdYUitsQ0FJeGhaWkNKMzQK17wUilUWxfWBwCSXr++W2wpAe6Nul3LG
            i/Xa0zu3u0ZJTvZQHsGWnPJkhBNk3s2DlDE4GzXmI9crEgKhQkqlAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-09T17:48:16Z"
    mac: ENC[AES256_GCM,data:TOWApaRyJhTTUlwe9WWq21cBkcFh6D3TS+vldq+T8/Aw1/sJ0q6keuf5cou+i6qQ3eG89/6nX71N6Ym71y6NjP4k9itlQ/II0aHW+WZpspuPeU+37YzyRr5l68CNo7cvWcyHYmx6gp6DjlVpK5NxWKwo6pLUzgn5/Hh8u42Bp5E=,iv:KBe0N3wH2XMowXqRevH0WrzdBX6E09PNEE60Gpm2mVI=,tag:yXc/YiJ7BcQoj7JZSMNobw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
