// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface GetPolicyRule {
    /**
     * Policy Rule Action (accept|drop)
     */
    action?: string;
    /**
     * Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
     */
    authorizedGroups?: {[key: string]: string[]};
    /**
     * Policy Rule Bidirectional
     */
    bidirectional?: boolean;
    /**
     * Policy description
     */
    description?: string;
    /**
     * Policy Rule Destination Resource (mutually exclusive with destinations)
     */
    destinationResource?: inputs.GetPolicyRuleDestinationResource;
    /**
     * Policy Rule Destination Groups (mutually exclusive with destination_resource)
     */
    destinations?: string[];
    /**
     * Policy Rule Enabled
     */
    enabled?: boolean;
    /**
     * Policy ID
     */
    id?: string;
    /**
     * Policy Name
     */
    name?: string;
    /**
     * Policy Rule Port Ranges (mutually exclusive with ports)
     */
    portRanges?: inputs.GetPolicyRulePortRange[];
    /**
     * Policy Rule Ports (mutually exclusive with port_ranges)
     */
    ports?: string[];
    /**
     * Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
     */
    protocol?: string;
    /**
     * Policy Rule Source Resource (mutually exclusive with sources)
     */
    sourceResource?: inputs.GetPolicyRuleSourceResource;
    /**
     * Policy Rule Source Groups (mutually exclusive with source_resource)
     */
    sources?: string[];
}

export interface GetPolicyRuleArgs {
    /**
     * Policy Rule Action (accept|drop)
     */
    action?: pulumi.Input<string | undefined>;
    /**
     * Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
     */
    authorizedGroups?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>} | undefined>;
    /**
     * Policy Rule Bidirectional
     */
    bidirectional?: pulumi.Input<boolean | undefined>;
    /**
     * Policy description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Policy Rule Destination Resource (mutually exclusive with destinations)
     */
    destinationResource?: pulumi.Input<inputs.GetPolicyRuleDestinationResourceArgs | undefined>;
    /**
     * Policy Rule Destination Groups (mutually exclusive with destination_resource)
     */
    destinations?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Policy Rule Enabled
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Policy ID
     */
    id?: pulumi.Input<string | undefined>;
    /**
     * Policy Name
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Policy Rule Port Ranges (mutually exclusive with ports)
     */
    portRanges?: pulumi.Input<pulumi.Input<inputs.GetPolicyRulePortRangeArgs>[] | undefined>;
    /**
     * Policy Rule Ports (mutually exclusive with port_ranges)
     */
    ports?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
     */
    protocol?: pulumi.Input<string | undefined>;
    /**
     * Policy Rule Source Resource (mutually exclusive with sources)
     */
    sourceResource?: pulumi.Input<inputs.GetPolicyRuleSourceResourceArgs | undefined>;
    /**
     * Policy Rule Source Groups (mutually exclusive with source_resource)
     */
    sources?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface GetPolicyRuleDestinationResource {
    id: string;
    type: string;
}

export interface GetPolicyRuleDestinationResourceArgs {
    id: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface GetPolicyRulePortRange {
    end?: number;
    start?: number;
}

export interface GetPolicyRulePortRangeArgs {
    end?: pulumi.Input<number | undefined>;
    start?: pulumi.Input<number | undefined>;
}

export interface GetPolicyRuleSourceResource {
    id: string;
    type: string;
}

export interface GetPolicyRuleSourceResourceArgs {
    id: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface NameserverGroupNameserver {
    /**
     * Nameserver IP
     */
    ip: pulumi.Input<string>;
    /**
     * Nameserver Type
     */
    nsType?: pulumi.Input<string | undefined>;
    /**
     * Nameserver Port
     */
    port?: pulumi.Input<number | undefined>;
}

export interface PolicyRule {
    /**
     * Policy Rule Action (accept|drop)
     */
    action?: pulumi.Input<string | undefined>;
    /**
     * Map of source group IDs to a list of local users authorized for SSH access. Keys must be group IDs present in <span pulumi-lang-nodejs="`sources`" pulumi-lang-dotnet="`Sources`" pulumi-lang-go="`sources`" pulumi-lang-python="`sources`" pulumi-lang-yaml="`sources`" pulumi-lang-java="`sources`">`sources`</span>. If not set, all local users are permitted. Only applicable when protocol is `netbird-ssh`.
     */
    authorizedGroups?: pulumi.Input<{[key: string]: pulumi.Input<pulumi.Input<string>[]>} | undefined>;
    /**
     * Policy Rule Bidirectional
     */
    bidirectional?: pulumi.Input<boolean | undefined>;
    /**
     * Policy description
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * Policy Rule Destination Resource (mutually exclusive with destinations)
     */
    destinationResource?: pulumi.Input<inputs.PolicyRuleDestinationResource | undefined>;
    /**
     * Policy Rule Destination Groups (mutually exclusive with destination_resource)
     */
    destinations?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Policy Rule Enabled
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Policy ID
     */
    id?: pulumi.Input<string | undefined>;
    /**
     * Policy Name
     */
    name: pulumi.Input<string>;
    /**
     * Policy Rule Port Ranges (mutually exclusive with ports)
     */
    portRanges?: pulumi.Input<pulumi.Input<inputs.PolicyRulePortRange>[] | undefined>;
    /**
     * Policy Rule Ports (mutually exclusive with port_ranges)
     */
    ports?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Policy Rule Protocol (tcp|udp|icmp|all|netbird-ssh)
     */
    protocol?: pulumi.Input<string | undefined>;
    /**
     * Policy Rule Source Resource (mutually exclusive with sources)
     */
    sourceResource?: pulumi.Input<inputs.PolicyRuleSourceResource | undefined>;
    /**
     * Policy Rule Source Groups (mutually exclusive with source_resource)
     */
    sources?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface PolicyRuleDestinationResource {
    id: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface PolicyRulePortRange {
    end: pulumi.Input<number>;
    start: pulumi.Input<number>;
}

export interface PolicyRuleSourceResource {
    id: pulumi.Input<string>;
    type: pulumi.Input<string>;
}

export interface PostureCheckGeoLocationCheck {
    action?: pulumi.Input<string | undefined>;
    locations?: pulumi.Input<pulumi.Input<inputs.PostureCheckGeoLocationCheckLocation>[] | undefined>;
}

export interface PostureCheckGeoLocationCheckLocation {
    cityName?: pulumi.Input<string | undefined>;
    countryCode: pulumi.Input<string>;
}

export interface PostureCheckNetbirdVersionCheck {
    minVersion?: pulumi.Input<string | undefined>;
}

export interface PostureCheckOsVersionCheck {
    androidMinVersion?: pulumi.Input<string | undefined>;
    darwinMinVersion?: pulumi.Input<string | undefined>;
    iosMinVersion?: pulumi.Input<string | undefined>;
    linuxMinKernelVersion?: pulumi.Input<string | undefined>;
    windowsMinKernelVersion?: pulumi.Input<string | undefined>;
}

export interface PostureCheckPeerNetworkRangeCheck {
    action?: pulumi.Input<string | undefined>;
    ranges?: pulumi.Input<pulumi.Input<string>[] | undefined>;
}

export interface PostureCheckProcessCheck {
    linuxPath?: pulumi.Input<string | undefined>;
    macPath?: pulumi.Input<string | undefined>;
    windowsPath?: pulumi.Input<string | undefined>;
}

export interface ReverseProxyServiceAuth {
    /**
     * Bearer token authentication
     */
    bearerAuth?: pulumi.Input<inputs.ReverseProxyServiceAuthBearerAuth | undefined>;
    /**
     * Link authentication
     */
    linkAuth?: pulumi.Input<inputs.ReverseProxyServiceAuthLinkAuth | undefined>;
    /**
     * Password authentication
     */
    passwordAuth?: pulumi.Input<inputs.ReverseProxyServiceAuthPasswordAuth | undefined>;
    /**
     * PIN authentication
     */
    pinAuth?: pulumi.Input<inputs.ReverseProxyServiceAuthPinAuth | undefined>;
}

export interface ReverseProxyServiceAuthBearerAuth {
    /**
     * List of group IDs that can use bearer auth
     */
    distributionGroups?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    enabled: pulumi.Input<boolean>;
}

export interface ReverseProxyServiceAuthLinkAuth {
    enabled: pulumi.Input<boolean>;
}

export interface ReverseProxyServiceAuthPasswordAuth {
    enabled: pulumi.Input<boolean>;
    password?: pulumi.Input<string | undefined>;
}

export interface ReverseProxyServiceAuthPinAuth {
    enabled: pulumi.Input<boolean>;
    pin?: pulumi.Input<string | undefined>;
}

export interface ReverseProxyServiceTarget {
    /**
     * Whether this target is enabled
     */
    enabled?: pulumi.Input<boolean | undefined>;
    /**
     * Backend IP or domain for this target. If omitted, the API resolves it from the target peer.
     */
    host?: pulumi.Input<string | undefined>;
    /**
     * URL path prefix for this target. Defaults to "/" if omitted.
     */
    path?: pulumi.Input<string | undefined>;
    /**
     * Backend port for this target (0 for scheme default)
     */
    port: pulumi.Input<number>;
    /**
     * Protocol to use when connecting to the backend (http, https)
     */
    protocol: pulumi.Input<string>;
    /**
     * Target ID (resource or peer ID)
     */
    targetId: pulumi.Input<string>;
    /**
     * Target type (peer, host, domain, subnet)
     */
    targetType: pulumi.Input<string>;
}
